version: "3.8"

services:
  utils-web-services:
    build: .
    container_name: utils-web-services
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # 持久化存储上传和下载的临时文件
      - ./data/uploads:/app/uploads
      - ./data/downloads:/app/downloads
    user: "1000:1000"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - utils-network

  # 可选：添加Nginx反向代理
  # nginx:
  #   image: nginx:alpine
  #   container_name: utils-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - utils-web-services
  #   restart: unless-stopped
  #   networks:
  #     - utils-network

networks:
  utils-network:
    driver: bridge

volumes:
  uploads-data:
  downloads-data:
