version: "3.8"

services:
  utils-web-services:
    build: .
    container_name: utils-web-services
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./data/uploads:/app/uploads
      - ./data/downloads:/app/downloads
    restart: unless-stopped
